name: pizza_market
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Local
  db_helper:
    path: packages/db_helper
  pizza_repo:
    path: packages/pizza_repo

  # Third party
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  generate: true
  uses-material-design: true
