name: pizza_repo
description: Pizza repository.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  # Local
  db_helper:
    path: ../db_helper

  # Third party
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0
  json_serializable: ^6.3.0
  lints: ^2.0.0
  test: ^1.16.0
